// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8z2jDx82jf5O3dA6CniIxrgaN0-LnHXQ',
    appId: '1:786012415585:web:89caadb9fe359ff7492c20',
    messagingSenderId: '786012415585',
    projectId: 'assignment-test-ca16c',
    authDomain: 'assignment-test-ca16c.firebaseapp.com',
    storageBucket: 'assignment-test-ca16c.appspot.com',
    measurementId: 'G-FFGWHM18EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvj9JBcPojlmq3eZ-yUTlsVfmM4rqOqk',
    appId: '1:786012415585:android:31b175ca15177379492c20',
    messagingSenderId: '786012415585',
    projectId: 'assignment-test-ca16c',
    storageBucket: 'assignment-test-ca16c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSh-TWwzMB8W-mFGzapnLzv2xI27BkPk',
    appId: '1:786012415585:ios:824a7001942c9df1492c20',
    messagingSenderId: '786012415585',
    projectId: 'assignment-test-ca16c',
    storageBucket: 'assignment-test-ca16c.appspot.com',
    iosClientId: '786012415585-g7kvbkms0apg77a52sr7dprcbtasupfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKSh-TWwzMB8W-mFGzapnLzv2xI27BkPk',
    appId: '1:786012415585:ios:13e83ed7e27b5365492c20',
    messagingSenderId: '786012415585',
    projectId: 'assignment-test-ca16c',
    storageBucket: 'assignment-test-ca16c.appspot.com',
    iosClientId: '786012415585-n8kme017eg4fa07rnms55p6r6j8akeeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
